version: '3.9'
services:
  delugeui:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: delugeui
    network_mode: "container:vpn"
    container_name: delugeui
    environment: 
      - LIBGL_ALWAYS_INDIRECT=1
    volumes:
      - /x:/x
      - /x/.config/delugeui:/root/.config/deluge