#!/usr/bin/bash
CONTAINER="vpn"
PID=""
for (( ; ; ))
do
  PID=$(docker inspect --format='{{ .State.Pid }}' ${CONTAINER} 2> /dev/null)
  if [ $? == 0 ]
  then
    echo found docker container ${CONTAINER} on pid ${PID}
    break
  fi
  echo waiting for docker container ${CONTAINER}
  sleep 1
done

for (( ; ; ))
do
  ip link set eth99 netns "${PID}" 2> /dev/null
  if [ $? == 0 ]
  then
    echo mapped eth99 to container
    break
  fi
  echo failed to map eth99 to container
  sleep 2
done