version: '3.9'
services:
    vpn:
      build:
        context: ./
        dockerfile: Dockerfile
      image: vpn
      container_name: vpn
      hostname: island
      cap_add:
        - NET_ADMIN
      restart: unless-stopped
      environment: 
        - CONFIG_FOLDER=/x/.config/vpn
      privileged: true
      network_mode: "bridge"
      volumes:
        - /x:/x
