version: '3.9'
services:
    vpn:
      build:
        context: ./
        dockerfile: Dockerfile
        args:
          TZ: US/Pacific
      image: vpn
      container_name: vpn
      hostname: vpn
      networks: 
        - vpnnet
      cap_add:
        - NET_ADMIN
      restart: unless-stopped
      environment: 
        - CONFIG_FOLDER=/x/.config/vpn 
      privileged: true
      volumes:
        - /x:/x

networks: 
  vpnnet:
    name: vpnnet
    driver: macvlan
    driver_opts:
      parent: eno2    
    ipam: 
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.99
          ip_range: 192.168.0.80/28
