version: '3.9'
services:
    vpn:
      build:
        context: ./
        dockerfile: Dockerfile
        args:
          TZ: US/Pacific
      image: vpn
      container_name: vpn
      hostname: vpn
      network_mode: bridge
      cap_add:
        - NET_ADMIN
      restart: no
      environment:
        - CONFIG_FOLDER=/config/vpn
      privileged: true
      volumes:
        - /docker/config:/config