version: '3.9'
services:
    vpn:
      build:
        context: ./
        dockerfile: Dockerfile
      image: vpn
      container_name: vpn
      hostname: island
      cap_add:
        - NET_ADMIN
      restart: unless-stopped
      secrets:
        - dnsup.conf
        - connected.conf
        - wg.tar.gz
      privileged: true
      network_mode: "bridge"

      
secrets:
  dnsup.conf:
    file: "../.secrets/dnsup.conf"
  connected.conf:
    file: "../.secrets/connected.conf"
  wg.tar.gz:
    file: "../.secrets/wg.tar.gz"