version: '3.9'
services:
  sonarr:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: sonarr
    container_name: sonarr
    network_mode: bridge    
    hostname: sonarr
    volumes:
      - /x:/x
      - /z:/z
      - /x/.config/sonarr:/home/jeremy/.config/sonarr
