version: '3.9'
services:
  tautulli:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: tautulli
    container_name: tautulli
    restart: unless-stopped
    network_mode: bridge    
    hostname: tautulli
    volumes:
      - /x/.config/tautulli:/config