version: '3.9'
services:
  # vpn:
  #   build:
  #     context: ./vpn/
  #     dockerfile: Dockerfile
  #     args:
  #       TZ: US/Pacific
  #   image: vpn
  #   container_name: vpn
  #   hostname: vpn
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped
  #   environment: 
  #     - CONFIG_FOLDER=/x/.config/vpn
  #   privileged: true
  #   networks: 
  #     vpnnet:
  #       ipv4_address: 192.168.0.80
  #   volumes:
  #     - /x:/x
  deluge_pub:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2
    container_name: deluge_pub
    restart: unless-stopped
    network_mode: bridge    
    hostname: deluge_pub
    volumes:
      - /x/.config/deluge_pub:/home/jeremy/.config/deluge
      - /x/.config/deluge_pub:/deluge
      - /x/.config/_recycle:/torrent_files
  deluge_ipt:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2 
    container_name: deluge_ipt
    restart: unless-stopped
    network_mode: bridge    
    hostname: deluge_ipt
    volumes:
      - /x/.config/deluge_ipt:/home/jeremy/.config/deluge
      - /x/.config/deluge_ipt:/deluge
      - /x/.config/_recycle:/torrent_files
      - /z/.seeds:/seeds
  deluge_tl:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2 
    container_name: deluge_tl
    network_mode: bridge    
    hostname: deluge_tl
    restart: unless-stopped
    volumes:
      - /x/.config/deluge_tl:/home/jeremy/.config/deluge
      - /x/.config/deluge_tl:/deluge
      - /x/.config/_recycle:/torrent_files
      - /z/.seeds:/seeds
  sabnzbd:
    build:
      context: ./sabnzbd/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: bridge
    hostname: sabnzbd
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - /x:/x    
      - /x/.config/.sabnzbd:/home/jeremy/.sabnzbd
  jackett_priv:
    build:
      context: ./jackett/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: jackett
    container_name: jackett_priv
    hostname: jackett_priv
    network_mode: bridge
    restart: unless-stopped
    environment: 
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /x:/x
      - /x/.config/jackett_priv:/home/jeremy/.config
  jackett_pub:
    build:
      context: ./jackett/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: jackett
    container_name: jackett_pub
    hostname: jackett_pub
    network_mode: bridge
    restart: unless-stopped
    environment: 
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /x:/x
      - /x/.config/jackett_pub:/home/jeremy/.config
  tautulli:
    build:
      context: ./tautulli/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: tautulli
    container_name: tautulli
    restart: unless-stopped
    network_mode: bridge    
    hostname: tautulli
    volumes:
      - /x/.config/tautulli:/config
