version: '3.9'
services:
  vpn:
    build:
      context: ./vpn/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
    image: vpn
    container_name: vpn
    hostname: vpn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment: 
      - CONFIG_FOLDER=/x/.config/vpn
    privileged: true
    networks: 
      vpnnet:
        ipv4_address: 192.168.0.80
    volumes:
      - /x:/x
  deluge_pub:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2
    container_name: deluge_pub
    restart: unless-stopped
    depends_on: 
      - vpn 
    networks: 
      vpnnet:
        ipv4_address: 192.168.0.81
    volumes:
      - /x/.config/deluge_pub:/home/jeremy/.config/deluge
      - /x:/x
  deluge_ipt:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2
    container_name: deluge_ipt
    restart: unless-stopped
    depends_on: 
      - vpn
    networks: 
      vpnnet:
        ipv4_address: 192.168.0.82
    volumes:
      - /x/.config/deluge_ipt:/home/jeremy/.config/deluge
      - /x:/x
      - /z/.seeds:/seeds
  deluge_tl:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2
    container_name: deluge_tl
    restart: unless-stopped
    depends_on: 
      - vpn
    networks: 
      vpnnet:
        ipv4_address: 192.168.0.83
    volumes:
      - /x/.config/deluge_tl:/home/jeremy/.config/deluge
      - /x:/x
  sabnzbd:
    build:
      context: ./sabnzbd/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: host
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - /x:/x    
      - /x/.config/.sabnzbd:/home/jeremy/.sabnzbd
  jackett_priv:
    build:
      context: ./jackett/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: jackett
    container_name: jackett_priv
    networks: 
      vpnnet:
        ipv4_address: 192.168.0.84
    restart: unless-stopped
    depends_on: 
      - vpn
    environment: 
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /x:/x
      - /x/.config/jackett_priv:/home/jeremy/.config
  jackett_pub:
    build:
      context: ./jackett/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: jackett
    container_name: jackett_pub
    networks: 
      vpnnet:
        ipv4_address: 192.168.0.85
    restart: unless-stopped
    depends_on: 
      - vpn
    environment: 
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /x:/x
      - /x/.config/jackett_pub:/home/jeremy/.config
  tautulli:
    build:
      context: ./tautulli/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: tautulli
    container_name: tautulli
    restart: unless-stopped
    depends_on: 
      - vpn
    networks: 
      vpnnet:
        ipv4_address: 192.168.0.86
    volumes:
      - /x/.config/tautulli:/config



networks: 
  vpnnet:
    name: vpnnet
    driver: macvlan
    driver_opts:
      parent: eno2    
    ipam: 
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.99
          ip_range: 192.168.0.80/28
