version: '3.9'
services:
  vpn:
    build:
      context: ./vpn/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
    image: vpn
    container_name: vpn
    hostname: island
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment: 
      - CONFIG_FOLDER=/x/.config/vpn
    privileged: true
    network_mode: "bridge"
    volumes:
      - /x:/x
  deluge_pub:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2
    container_name: deluge_pub
    restart: unless-stopped
    network_mode: "service:vpn"
    volumes:
      - /x/.config/deluge_pub:/home/jeremy/.config/deluge
      - /x:/x
  deluge_ipt:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2
    container_name: deluge_ipt
    restart: unless-stopped
    network_mode: "service:vpn"
    volumes:
      - /x/.config/deluge_ipt:/home/jeremy/.config/deluge
      - /x:/x
      - /z/.seeds:/seeds
  deluge_tl:
    build:
      context: ./deluge2/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2
    container_name: deluge_tl
    restart: unless-stopped
    network_mode: "service:vpn"
    volumes:
      - /x/.config/deluge_tl:/home/jeremy/.config/deluge
      - /x:/x
  sabnzbd:
    build:
      context: ./sabnzbd/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
        SERVER_PORT: 59354
    image: sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: "service:vpn"
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - /x:/x    
      - /x/.config/.sabnzbd:/home/jeremy/.sabnzbd
  jackett_priv:
    build:
      context: ./jackett/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: jackett
    container_name: jackett_priv
    network_mode: "service:vpn"
    restart: unless-stopped
    environment: 
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /x:/x
      - /x/.config/jackett_priv:/home/jeremy/.config
  jackett_pub:
    build:
      context: ./jackett/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: jackett
    container_name: jackett_pub
    network_mode: "service:vpn"
    restart: unless-stopped
    environment: 
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /x:/x
      - /x/.config/jackett_pub:/home/jeremy/.config
  # hydra:
  #   build:
  #     context: ./hydra/
  #     dockerfile: Dockerfile
  #     args:
  #       TZ: US/Pacific
  #       USER: jeremy
  #   image: hydra
  #   container_name: hydra
  #   restart: unless-stopped
  #   network_mode: "service:vpn"
  #   secrets:
  #     - hydra.conf
  #   depends_on: 
  #     - deluge_pub
  #     - deluge_tl
  #     - deluge_ipt
  #     - sonarr  
  #   volumes:
  #     - /x:/x
  #     - /z:/z
  # sonarr: <- runs container as separate systemd service now
  #   build:
  #     context: ./sonarr/
  #     dockerfile: Dockerfile
  #     args:
  #       TZ: US/Pacific
  #       USER: jeremy
  #   image: sonarr
  #   container_name: sonarr
  #   network_mode: "service:vpn"
  #   restart: unless-stopped
  #   depends_on: 
  #     - sabnzbd
  #   volumes:
  #     - /x:/x
  #     - /z:/z
  #     - /x/.config/sonarr:/home/jeremy/.config/sonarr
  tautulli:
    build:
      context: ./tautulli/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: tautulli
    container_name: tautulli
    restart: unless-stopped
    network_mode: "service:vpn"
    volumes:
      - /x/.config/tautulli:/config


