# prereq 
# docker build -t secrets .secrets

version: '3.8'
services:
  vpn:
    build:
      context: ./vpn/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
    image: vpn
    container_name: vpn
    hostname: island
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    privileged: true
    network_mode: "bridge"
  deluge_pub:
    build:
      context: ./deluge/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge
    container_name: deluge_pub
    restart: unless-stopped
    network_mode: "service:vpn"
    volumes:
      - /x/.config/deluge_pub:/home/jeremy/.config/deluge
      - /x:/x
  deluge_ipt:
    build:
      context: ./deluge/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge
    container_name: deluge_ipt
    restart: unless-stopped
    network_mode: "service:vpn"
    volumes:
      - /x/.config/deluge_ipt:/home/jeremy/.config/deluge
      - /x:/x
  deluge_tl:
    build:
      context: ./deluge/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge
    container_name: deluge_tl
    restart: unless-stopped
    network_mode: "service:vpn"
    volumes:
      - /x/.config/deluge_tl:/home/jeremy/.config/deluge
      - /x:/x
  sabnzbd:
    build:
      context: ./sabnzbd/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
        SERVER_PORT: 59354
    image: sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: "service:vpn"
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - /x:/x    
      - /x/.config/.sabnzbd:/home/jeremy/.sabnzbd
  jackett_priv:
    build:
      context: ./jackett/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: jackett
    container_name: jackett_priv
    network_mode: "service:vpn"
    restart: unless-stopped
    environment: 
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /x:/x
      - /x/.config/jackett_priv:/home/jeremy/.config
  jackett_pub:
    build:
      context: ./jackett/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: jackett
    container_name: jackett_pub
    network_mode: "service:vpn"
    restart: unless-stopped
    environment: 
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /x:/x
      - /x/.config/jackett_pub:/home/jeremy/.config
  hydra:
    build:
      context: ./hydra/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: hydra
    container_name: hydra
    restart: unless-stopped
    network_mode: "service:vpn"
    depends_on: 
      - deluge_pub
      - deluge_tl
      - deluge_ipt  
    volumes:
      - /x:/x
      - /z:/z
  sonarr:
    build:
      context: ./sonarr/
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: sonarr
    container_name: sonarr
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on: 
      - sabnzbd
    volumes:
      - /x:/x
      - /z:/z
      - /x/.config/sonarr:/home/jeremy/.config/sonarr

