version: '3.9'
services:
  deluge_pub:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2
    container_name: deluge_pub
    restart: unless-stopped
    network_mode: bridge    
    hostname: deluge_pub
    volumes:
      - /x/.config/deluge_pub:/home/jeremy/.config/deluge
      - /x/.config/deluge_pub:/deluge
      - /x/.config/_recycle:/torrent_files
      - /z/.seeds:/seeds
  deluge_ipt:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2 
    container_name: deluge_ipt
    restart: unless-stopped
    network_mode: bridge    
    hostname: deluge_ipt
    volumes:
      - /x/.config/deluge_ipt:/home/jeremy/.config/deluge
      - /x/.config/deluge_ipt:/deluge
      - /x/.config/_recycle:/torrent_files
      - /z/.seeds:/seeds
  deluge_tl:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge2 
    container_name: deluge_tl
    network_mode: bridge    
    hostname: deluge_tl
    restart: unless-stopped
    volumes:
      - /x/.config/deluge_tl:/home/jeremy/.config/deluge
      - /x/.config/deluge_tl:/deluge
      - /x/.config/_recycle:/torrent_files
      - /z/.seeds:/seeds