version: '3.8'
services:
  hydra:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: hydra
    container_name: hydra
    restart: unless-stopped
    network_mode: "container:vpn"
    volumes:
      - /x:/x
      - /z:/z
