version: '3.9'
services:
  hydra:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: hydra
    container_name: hydra
    restart: unless-stopped
    network_mode: "container:vpn"
    secrets:
      - hydra.conf
    volumes:
      - /x:/x
      - /z:/z

secrets:
  hydra.conf:
    file: "../.secrets/hydra.conf"
      