version: '3.9'
services:
  sabnzbd:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: sabnzbd
    hostname: sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: bridge
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - /x:/x    
      - /x/.config/.sabnzbd:/home/jeremy/.sabnzbd