version: '3.8'
services:
  sabnzbd:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
        SERVER_PORT: 59354
    image: sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: "container:vpn"
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - /x:/x    
      - /x/.config/.sabnzbd:/home/jeremy/.sabnzbd