version: '3.9'
services:
    vpn:
      build:
        context: ./
        dockerfile: Dockerfile
      image: ubuntu:latest 
      container_name: ubuntu
      hostname: ubu 
      cap_add:
        - NET_ADMIN
      privileged: true
      network_mode: "bridge"
      volumes:
        - /x:/x
