version: '3.8'
services:
  radarr:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: radarr
    container_name: radarr
    network_mode: "container:vpn"
    volumes:
      - /x:/x
      - /z:/z
      - /x/.config/radarr:/home/jeremy/.config/radarr