#!/bin/sh
echo setting ip address tp $IP
ip addr flush dev eth0
ip addr add $IP/24 dev eth0
echo setting default gateway to $GW
ip route del default
ip route add default via $GW dev eth0
echo starting jackett
/Jackett/jackett_launcher.sh