version: '3.9'
services:
  cloudflared:
    image: cloudflare/cloudflared
    network_mode: host
    container_name: cloudflared
    command: "proxy-dns --address 0.0.0.0"
    restart: unless-stopped
    user: 0:0

