version: '3.9'
services:
  deluge_pub:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge
    container_name: deluge_pub
    restart: unless-stopped
    network_mode: "container:vpn"
    volumes:
      - /x/.config/deluge_pub:/home/jeremy/.config/deluge
      - /x:/x
  deluge_ipt:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge
    container_name: deluge_ipt
    restart: unless-stopped
    network_mode: "container:vpn"
    volumes:
      - /x/.config/deluge_ipt:/home/jeremy/.config/deluge
      - /x:/x
      - /z/.seeds:/seeds
  deluge_tl:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: deluge
    container_name: deluge_tl
    restart: unless-stopped
    network_mode: "container:vpn"
    volumes:
      - /x/.config/deluge_tl:/home/jeremy/.config/deluge
      - /x:/x