version: '3.9'
services:
  portcheck:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: portcheck
    container_name: portcheck
    restart: unless-stopped
    network_mode: "container:vpn"
    environment: 
      - CONFIG_FOLDER=/x/.config/vpn
    volumes:
      - /x:/x
     