version: '3.9'
services:
  yt:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: US/Pacific
        USER: jeremy
    image: yt
    network_mode: bridge
    container_name: yt
    volumes:
      - /x:/x
      - /z:/z
